### ISSUE TITLE
Import new set of icons

### ISSUE THREAD

**Issue by werdahias** [Fausto-Korpsvart/Gruvbox-GTK-Theme#10]
I really like your theme. However, I use [these](https://www.opencode.net/adhe/gruvboxplasma) icons: They are based on papirus with a gruvbox tint. The upstream seems to be dead. I'd appriciate if you could maybe integrate these into your project and update, if possible.

Cheers

**Comment by Fausto-Korpsvart** [comment]
> I really like your theme. However, I use [these](https://www.opencode.net/adhe/gruvboxplasma) icons: They are based on papirus with a gruvbox tint. The upstream seems to be dead. I'd appriciate if you could maybe integrate these into your project and update, if possible.
> 
> Cheers

I remember these icons you mention, you are right, they are great, unfortunately I don't have experience creating icon themes, I can't promise anything because I am just starting to understand about how icon themes work, maybe in the future I can start adding another icon theme different from Suru.

Thanks for your support and for reporting. };-]

**Comment by goosegit11** [comment]
You actually can use any GTK theme with any icons.
use LXAppearance for that.

**Comment by Goosegit11** [comment]
Or nwg-look.
