### ISSUE TITLE
Flatpak applications default to light theme

### ISSUE THREAD

**Issue by telometto** [Fausto-Korpsvart/Gruvbox-GTK-Theme#12]
Using `Adwaita-dark` in GNOME Tweaks makes all the Flatpak applications dark. When I use your theme they default to light theming and, unfortunately, many of the apps do not allow to change the theme...

Is there any way to make Flatpak applications default to dark theming/Adwaita-dark by using this theme?

**Comment by Fausto-Korpsvart** [comment]
> Using `Adwaita-dark` in GNOME Tweaks makes all the Flatpak applications dark. When I use your theme they default to light theming and, unfortunately, many of the apps do not allow to change the theme...
> 
> Is there any way to make Flatpak applications default to dark theming/Adwaita-dark by using this theme?

[Here](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/issues/17#issuecomment-1214413913) We've been talking about it, you could have a look and see if the links can help you, because if it's a problem mostly with Flatpak and not with the theme itself.
Check the conversation and the links and let me know if the problem is solved.

**Comment by telometto** [comment]
Thanks for the swift reply. I managed to find something which allows for themes to be installed and used on Flatpaks as well. I created a pull request for the documentation 😊
