### ISSUE TITLE
The name is very confusing

### ISSUE THREAD

**Issue by Noob-linux-user** [Fausto-Korpsvart/Gruvbox-GTK-Theme#14]
In the ping store, it is very confusing to download a theme. There are so many abbreviations by bl, b, bl, light, bl dark. Can you show some screenshot and specify what is the name of that specific version?

**Comment by Fausto-Korpsvart** [comment]
> In the ping store, it is very confusing to download a theme. There are so many abbreviations by bl, b, bl, light, bl dark. Can you show some screenshot and specify what is the name of that specific version?

Sorry it took me so long to reply.

In Pling, when you go to the download section, in Files, in the description part you can see, with a bit of logic, what the abbreviations B, BL, LB, etc. are about. 
For example: Border = B, Borderless = BL, Legacy Buttons = LB, Gnome 42 = G42; the problem is that I can't put extremely descriptive names on the packages, so I've tried to shorten the very long names a bit; in the general description part, always in Pling, there is also a description of how the abbreviations work.

But I will update the description and screenshots to try to explain the names better.

Thanks for your suggestion and support. };-]

**Comment by Noob-linux-user** [comment]
Thanks, having more screenshot is always better. Btw, your themes are awesome. Have a lovely day.
