### ISSUE TITLE
Naming confiusion

### ISSUE THREAD

**Issue by pietryszak** [Fausto-Korpsvart/Gruvbox-GTK-Theme#17]
Ok so I wanna use gruvbox without borders. 

I shoud install GTK3 and GTK4 theme from folders. GTK4 to ~/.config/gtk-4.0, GTK 3 to ~/.themes/.
What with GTK2, I see a folder with that.

And I use tilling manager like i3-gaps. I don't use Gnome. I shoud use Gruvbox-Dark-BL or Gruvbox-Dark-BL-LB?
Where put GTK2 theme?

Naming shoud be like gruvbox-dark-with-borders and grubvox-dark-without-borders, gruvbox-dark-with-borders-gnome-42+, grubvox-without-borders-gnome-42+

Non technical users, dont know what libadwaita means. They knows i have gnome 42, so i shoud use package with name 42+ with or without borders.

**Comment by Fausto-Korpsvart** [comment]
> Ok so I wanna use gruvbox without borders.
> 
> I shoud install GTK3 and GTK4 theme from folders. GTK4 to ~/.config/gtk-4.0, GTK 3 to ~/.themes/. What with GTK2, I see a folder with that.
> 
> And I use tilling manager like i3-gaps. I don't use Gnome. I shoud use Gruvbox-Dark-BL or Gruvbox-Dark-BL-LB? Where put GTK2 theme?
> 
> Naming shoud be like gruvbox-dark-with-borders and grubvox-dark-without-borders, gruvbox-dark-with-borders-gnome-42+, grubvox-without-borders-gnome-42+
> 
> Non technical users, dont know what libadwaita means. They knows i have gnome 42, so i shoud use package with name 42+ with or without borders.

Yes, you're not the first to suggest a name change because it's a bit confusing, but I'll update the description soon to clarify the abbreviations.

I've put abbreviations because I don't want to put too long names, for example: Gruvbox-Borderless-Legacy-Buttons-Gnome-42, that's too long, so I opted to abbreviate it to: `B = Border`, `BL = Borderless`, `LB = Legacy Buttons`, `G42 = Gnome 42`.
If the theme you want to use is the Borderless theme, you should install the `Gruvbox BL` themes; the themes that don't have Legacy Buttons use the macOS-style window control buttons, so, if you don't want macOS-style buttons, you should install the themes that have `Legacy Buttons = LB`

Regarding `libadwaita`, since you don't use Gnome, you don't need to install the Gnome 42 theme, as this is only for Gnome specific applications.

To install the theme, just copy the `Gruvbox-Dark-BL` folder into the `.themes` directory.

As I said before, I will update the description soon to make it less confusing with so many abbreviations.

Thanks for reporting and your support.
