### ISSUE TITLE
Black corners on drop-down menus

### ISSUE THREAD

**Issue by Goosegit11** [Fausto-Korpsvart/Gruvbox-GTK-Theme#33]
https://www.reddit.com/r/gnome/comments/zubm5f/black_corners_on_rounded_gtk_themes_whats_the/
https://www.reddit.com/r/i3wm/comments/s2oceb/how_can_i_get_rid_of_black_color_behind_the_round/

I have this problem as well and I searched all over the internet for a solution, but I have not found one. Seems like the problem is not window manager or compositor, the problem is in your theme. 

I use dwm and picom, and every drop-down menu have that weird black corners. 
Thunar, Gajim, Transmission-gtk and others

Actually there is a workaround - put the corner-radius in picom.conf to ~12, then these corners will be hidden, but some people don't want round windows, so it's kinda silly hack

![image](https://user-images.githubusercontent.com/89806596/221660479-43155434-14b2-4f9a-90d2-2e21348509bb.png)

**Comment by Fausto-Korpsvart** [comment]
> https://www.reddit.com/r/gnome/comments/zubm5f/black_corners_on_rounded_gtk_themes_whats_the/ https://www.reddit.com/r/i3wm/comments/s2oceb/how_can_i_get_rid_of_black_color_behind_the_round/
> 
> I have this problem as well and I searched all over the internet for a solution, but I have not found one. Seems like the problem is not window manager or compositor, the problem is in your theme.
> 
> I use dwm and picom, and every drop-down menu have that weird black corners. Thunar, Gajim, Transmission-gtk and others
> 
> Actually there is a workaround - put the corner-radius in picom.conf to ~12, then these corners will be hidden, but some people don't want round windows, so it's kinda silly hack
> 
> ![image](https://user-images.githubusercontent.com/89806596/221660479-43155434-14b2-4f9a-90d2-2e21348509bb.png)

As far as I understand, this is not a problem with the theme, but rather with the compositor or with some kind of effects that you have activated, for example blur.

I remember that in XFCE there was a similar problem with Plank Dock, a shadow appeared that showed all the desktop space used by the Dock elements, if I remember correctly, it was solved by disabling the compositor effects for the Dock and Panels, in Gnome something like this happens with Dash To Dock when you add the Blur effects extension, it shows square corners and not round as the theme has determined.
I also remember having this problem with XmonadWM, the GTK themes with round corners had the corners squared by the Comptom or Picom compositor, I don't remember which version I was using back then, but it added the blur effect which made the corners show square and not round.

Anyway, I'm going to check it out and look for a solution.

Thanks for the report and for the support, and sorry for the delay in replying, work is taking away my time to dedicate to the project at the moment.

**Comment by Fausto-Korpsvart** [comment]
> It's the same with or without the compositor. Can be fixed by picom with rounded corners, but then you'll have rounded corners on every window (not only drop-down menus). So it's just a workaround, not a solution

Well, I think there is no concrete solution for this, since these themes are made for Gnome WM, not for TWM, those elements that do not render well are the shadows that are handled from the GTK theme.

In the Reddit links I read something about excluding some GTK rules from the Picom settings so that this behavior doesn't occur, since Picom, for example, handles shadows and rounded corners from its own settings file, which conflicts with the shadows and decorations typical of the GTK theme.
I haven't tried this solution yet due to lack of time, so I don't know if that option gives a way to handle this behavior.

The solution to completely avoid this would be to remove the rounded corners from the GTK theme, so it wouldn't conflict with the effects the composers provide.

**Comment by Fausto-Korpsvart** [comment]
> So if you remove the shadows from the theme, it would be fine on TWMs?

Yes, and in fact I think it's the only solution for TWMs, but the problem is that it wouldn't work very well without the shadows on the Gnome desktop, that's why I can remove the leftovers in the themes.

I don't want to promise anything, because due to my work I can't dedicate much time as I would like to this project, but I will try to work a version without shadows for TWMs, first I have to do a lot of tests, because I have tried few TWMs like BSPWM, Awsome and QTile, but the one I liked the most is Xmonad, and this is the one I have used for more time.

So, as I said, no promises, but I'll try, as I have to update the Gnome themes for the moment.

**Comment by Goosegit11** [comment]
Thank you, I'm willing to help with testing!

**Comment by ironhak** [comment]
The problem persist in xfce. 
![image](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/62611612/c0361fb3-1d49-444f-a00e-9237b2395365)

**Comment by Goosegit11** [comment]
Not completed.

**Comment by Fausto-Korpsvart** [comment]
> Not completed.

@ironhak, @Goosegit11.

As I have already explained, this is not a problem with the theme, it is a problem with the Compositor, if it is disabled it will always show that annoying black border, but if you turn it on it disappears and in its place there is a soft shadow.

Compositor disabled

![XFCE-Compositor1](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/47998118/a1caae5e-0e5c-458a-8742-456810b7cfc9)

Compositor enabled

![XFCE-Compositor2](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme/assets/47998118/b3c731b9-b6c2-4d20-bdab-407155b5abfe)

**Comment by ironhak** [comment]
> Compositor, if it is disabled it will always show that annoying black border, but if you turn it on it disappears and in its place there is a soft shad

@Fausto-Korpsvart  Hello thank's, but what's the difference of using Xfce + Compositor vs Xfce vs Xfce + Compton?
Thank's
