### ISSUE TITLE
Buggy Borders

### ISSUE THREAD

**Issue by hekki0n** [Fausto-Korpsvart/Gruvbox-GTK-Theme#38]
The borders around certain applications appear buggy
![image](https://user-images.githubusercontent.com/132341103/236406095-e35cfdd5-eecd-4f82-9219-3a04b824a906.png)

**Comment by hekki0n** [comment]
This seems to be a issue with the new gnome version:
https://github.com/catppuccin/gtk/issues/92

**Comment by Fausto-Korpsvart** [comment]
> This seems to be a issue with the new gnome version: [catppuccin/gtk#92](https://github.com/catppuccin/gtk/issues/92)

Greetings, @hekki0n.

Just yesterday I noticed this while fixing bugs in the themes; then I updated the repository of the base theme, `Graphite`, but the bug was still there, I was looking for solutions and found the same information, it seems that the bug is from `Mutter` and not from the GTK themes.
I also noticed that it only affects applications that I installed via `Flatpak`, as I did some tests installing versions of `RPM` and `Flakpak` packages and I noticed that the bug affects `Flatpak` packages, but I'm not sure.

It seems that the bug is that `Mutter` doesn't render shadows properly, so I want to test by disabling shadows in the theme to see if my suspicion is correct.

So what's left is just to wait for the GNOME developers to fix the problem.

Thanks for reporting and for your support.
