### ISSUE TITLE
css warning

### ISSUE THREAD

**Issue by eeeXun** [Fausto-Korpsvart/Gruvbox-GTK-Theme#6]
I check the `~/.xsession-errors`. There is some warning.

```
(nm-applet:671): Gtk-WARNING **: 21:47:52.014: Theme parsing error: gtk.css:22798:24: not a number
(nm-applet:671): Gtk-WARNING **: 21:47:52.015: Theme parsing error: gtk.css:23580:24: not a number
```

Not only `nm-applet` has this problem. My file manager `caja` also has this warning.
I use `Gruvbox-Dark-BL` theme and `gruvbox_dark` icon.

**Comment by sodic** [comment]
Hi, I ran into the same problem. Until Fausto finds the time to address it, you can get rid of the warnings manually by editing the reported lines in the CSS file.

For example, line `22798` contains the following property:
```css
box-shadow: inset 1px rgba(249, 245, 215, 0.1);
```
GTK complains because this is not valid CSS (probably because of a bug in the theme creation tool). I don't know how this border was originally supposed to look like, but we can easily fix the CSS. It might not be what the author originally intended, but at least it will get rid of the warnings for the time being:
```css
box-shadow: inset 0 0 0 1px rgba(249, 245, 215, 0.1);
```
If you see the difference in the UI when changing this property (I don't), you can play around with its value and see what you like best. Read more about all possible values [on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow).

**Comment by Fausto-Korpsvart** [comment]
> 

Greetings, @eeeXun, @sodic, in the next update it will be solved, sorry for not doing it soon, because of my work I have only dedicated my free time to GTK themes, but soon I will do an update; and in fact this was a mistake on my part because that line is not necessary at all, and it does make a difference when placing the values: 'box-shadow: inset 0 0 0 1px rgba(249, 245, 215, 0. 1);' as it obviously draws the line on all four sides, so you'll notice a line under the title bar, a line that shouldn't be there and that's why 'box-shadow: inset' isn't really necessary.

@sodic, I'm not using a theme creation tool, nor a CSS framework, I'm doing it with pure CSS to learn a bit about how GTK themes work, probably for that reason it also takes me a bit more time, it's just me and my Neovim, in fact, outside the Oomox theme generator, I had no idea there was any theme creation tool for GTK, could you mention one? So I can check it out and see if it can help me and speed up theme creation and troubleshooting, I'd really appreciate it.

Thanks to both of you for reporting and providing solutions and support, it's great. };-]

**Comment by sodic** [comment]
Hey @Fausto-Korpsvart, don't stress about taking your time to fix something. It's a free and open-source project, after all. We're delighted to be getting such a beautiful theme, regardless of how long it takes :)

I had no idea you were doing it all in pure CSS. That's crazy impressive! I wondered how you achieved such a high level of customization compared to other themes I found. Well, mystery solved.

The only theme creation tool I know of is Oomox (i.e., Themix). I now see the README mentions you've used it in the past. I've never used it myself, but from what I understand (and from what you corroborated), it probably doesn't provide the kind of flexibility you would need.

It looks fantastic on Manjaro i3 btw. The only noticeable issue I have is small UI icons caused by HiDPI, but this isn't specific to your theme (it happens with the default ones as well). It's most likely related to the specifics of my setup and not a mistake in the themes. Still, if I figure out how to fix it and it ends up being a theme issue, I'll submit a PR :)

Anyway, loving the theme, and keep up the excellent work!

**Comment by eeeXun** [comment]
No this error in de19d2bb898405d0f316f563e7bb7501a5e44516
